from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Optional

import httpx
from fastapi import HTTPException
from sqlalchemy import delete, select
from sqlalchemy.ext.asyncio import AsyncSession

from db.models import RouteAlternative, RoutePlan, Trip

OSRM_ROUTE_URL = "https://router.project-osrm.org/route/v1/driving"


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


async def _fetch_route(origin_lat: float, origin_lng: float, destination_lat: float, destination_lng: float):
    coords = f"{origin_lng},{origin_lat};{destination_lng},{destination_lat}"
    url = f"{OSRM_ROUTE_URL}/{coords}?overview=full&geometries=geojson&alternatives=true"
    async with httpx.AsyncClient(timeout=15.0) as client:
        res = await client.get(url)
        res.raise_for_status()
        data = res.json()
    if data.get("code") != "Ok" or not data.get("routes"):
        raise HTTPException(status_code=502, detail="OSRM did not return a valid route")
    return data


def _fuel_estimate(distance_km: Optional[float]) -> Optional[float]:
    if distance_km is None:
        return None
    return round(distance_km * 0.32, 2)


async def build_route_plan(db: AsyncSession, trip: Trip) -> RoutePlan:
    if None in (trip.origin_lat, trip.origin_lng, trip.destination_lat, trip.destination_lng):
        raise HTTPException(status_code=400, detail="Trip is missing route coordinates")

    data = await _fetch_route(trip.origin_lat, trip.origin_lng, trip.destination_lat, trip.destination_lng)
    routes = data["routes"]
    primary = routes[0]
    eta = (trip.scheduled_departure or _utcnow()) + timedelta(seconds=primary.get("duration", 0))

    existing = (await db.execute(select(RoutePlan).where(RoutePlan.trip_id == trip.id))).scalar_one_or_none()
    if existing:
        await db.execute(delete(RouteAlternative).where(RouteAlternative.route_plan_id == existing.id))
        route_plan = existing
    else:
        route_plan = RoutePlan(trip_id=trip.id)
        db.add(route_plan)

    route_plan.origin_lat = trip.origin_lat
    route_plan.origin_lng = trip.origin_lng
    route_plan.destination_lat = trip.destination_lat
    route_plan.destination_lng = trip.destination_lng
    route_plan.route_geometry_ref = primary.get("geometry", {}).get("coordinates") and str(primary["geometry"]["coordinates"])
    route_plan.distance_km = round(primary.get("distance", 0) / 1000, 2)
    route_plan.duration_secs = round(primary.get("duration", 0), 2)
    route_plan.eta_at = eta
    route_plan.optimization_source = "osrm"
    route_plan.score = round((route_plan.distance_km or 0) + ((route_plan.duration_secs or 0) / 3600), 2)
    route_plan.generated_at = _utcnow()

    await db.flush()

    for idx, route in enumerate(routes[:3], start=1):
        db.add(RouteAlternative(
            route_plan_id=route_plan.id,
            label="Recommended" if idx == 1 else f"Alternative {idx - 1}",
            geometry_ref=route.get("geometry", {}).get("coordinates") and str(route["geometry"]["coordinates"]),
            distance_km=round(route.get("distance", 0) / 1000, 2),
            duration_secs=round(route.get("duration", 0), 2),
            fuel_estimate=_fuel_estimate(route.get("distance", 0) / 1000),
            rank=idx,
            notes="Lowest combined distance and duration" if idx == 1 else "Generated by OSRM alternatives",
        ))

    await db.commit()
    await db.refresh(route_plan)
    return route_plan


async def get_route_plan(db: AsyncSession, trip_id: str) -> Optional[RoutePlan]:
    return (await db.execute(select(RoutePlan).where(RoutePlan.trip_id == trip_id))).scalar_one_or_none()


async def get_route_alternatives(db: AsyncSession, route_plan_id: str) -> list[RouteAlternative]:
    return (await db.execute(
        select(RouteAlternative)
        .where(RouteAlternative.route_plan_id == route_plan_id)
        .order_by(RouteAlternative.rank.asc())
    )).scalars().all()


async def optimize_ad_hoc(origin_lat: float, origin_lng: float, destination_lat: float, destination_lng: float) -> dict:
    data = await _fetch_route(origin_lat, origin_lng, destination_lat, destination_lng)
    primary = data["routes"][0]
    return {
        "route_geometry_ref": str(primary.get("geometry", {}).get("coordinates", [])),
        "distance_km": round(primary.get("distance", 0) / 1000, 2),
        "duration_secs": round(primary.get("duration", 0), 2),
        "fuel_estimate": _fuel_estimate(primary.get("distance", 0) / 1000),
    }
