/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthTripsIndexRouteImport } from './routes/_auth/trips/index'
import { Route as AuthNotificationsIndexRouteImport } from './routes/_auth/notifications/index'
import { Route as AuthMaintenanceIndexRouteImport } from './routes/_auth/maintenance/index'
import { Route as AuthFuelIndexRouteImport } from './routes/_auth/fuel/index'
import { Route as AuthDriversIndexRouteImport } from './routes/_auth/drivers/index'
import { Route as AuthTripsNewRouteImport } from './routes/_auth/trips/new'
import { Route as AuthSettingsSystemRouteImport } from './routes/_auth/settings/system'
import { Route as AuthSettingsProfileRouteImport } from './routes/_auth/settings/profile'
import { Route as AuthDriversNewRouteImport } from './routes/_auth/drivers/new'
import { Route as AuthDriversDriverIdRouteImport } from './routes/_auth/drivers/$driverId'
import { Route as AuthTripsTripIdIndexRouteImport } from './routes/_auth/trips/$tripId/index'
import { Route as AuthSettingsUsersIndexRouteImport } from './routes/_auth/settings/users/index'
import { Route as AuthFleetTrucksIndexRouteImport } from './routes/_auth/fleet/trucks/index'
import { Route as AuthFleetTrailersIndexRouteImport } from './routes/_auth/fleet/trailers/index'
import { Route as AuthTripsTripIdEditRouteImport } from './routes/_auth/trips/$tripId/edit'
import { Route as AuthSettingsUsersNewRouteImport } from './routes/_auth/settings/users/new'
import { Route as AuthMaintenanceWorkOrdersNewRouteImport } from './routes/_auth/maintenance/work-orders/new'
import { Route as AuthMaintenanceSchedulesNewRouteImport } from './routes/_auth/maintenance/schedules/new'
import { Route as AuthFuelLogsNewRouteImport } from './routes/_auth/fuel/logs/new'
import { Route as AuthFuelExpensesNewRouteImport } from './routes/_auth/fuel/expenses/new'
import { Route as AuthFleetTrucksNewRouteImport } from './routes/_auth/fleet/trucks/new'
import { Route as AuthFleetTrucksTruckIdRouteImport } from './routes/_auth/fleet/trucks/$truckId'
import { Route as AuthFleetTrailersNewRouteImport } from './routes/_auth/fleet/trailers/new'
import { Route as AuthFleetTrailersTrailerIdRouteImport } from './routes/_auth/fleet/trailers/$trailerId'
import { Route as AuthDriversDriverIdEditRouteImport } from './routes/_auth/drivers/$driverId/edit'
import { Route as AuthMaintenanceWorkOrdersWorkOrderIdIndexRouteImport } from './routes/_auth/maintenance/work-orders/$workOrderId/index'
import { Route as AuthFuelLogsLogIdIndexRouteImport } from './routes/_auth/fuel/logs/$logId/index'
import { Route as AuthFuelExpensesExpenseIdIndexRouteImport } from './routes/_auth/fuel/expenses/$expenseId/index'
import { Route as AuthSettingsUsersUserIdEditRouteImport } from './routes/_auth/settings/users/$userId/edit'
import { Route as AuthMaintenanceWorkOrdersWorkOrderIdEditRouteImport } from './routes/_auth/maintenance/work-orders/$workOrderId/edit'
import { Route as AuthMaintenanceSchedulesScheduleIdEditRouteImport } from './routes/_auth/maintenance/schedules/$scheduleId/edit'
import { Route as AuthFleetTrucksTruckIdEditRouteImport } from './routes/_auth/fleet/trucks/$truckId.edit'
import { Route as AuthFleetTrailersTrailerIdEditRouteImport } from './routes/_auth/fleet/trailers/$trailerId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTripsIndexRoute = AuthTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNotificationsIndexRoute = AuthNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMaintenanceIndexRoute = AuthMaintenanceIndexRouteImport.update({
  id: '/maintenance/',
  path: '/maintenance/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFuelIndexRoute = AuthFuelIndexRouteImport.update({
  id: '/fuel/',
  path: '/fuel/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDriversIndexRoute = AuthDriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTripsNewRoute = AuthTripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsSystemRoute = AuthSettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDriversNewRoute = AuthDriversNewRouteImport.update({
  id: '/drivers/new',
  path: '/drivers/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDriversDriverIdRoute = AuthDriversDriverIdRouteImport.update({
  id: '/drivers/$driverId',
  path: '/drivers/$driverId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTripsTripIdIndexRoute = AuthTripsTripIdIndexRouteImport.update({
  id: '/trips/$tripId/',
  path: '/trips/$tripId/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsUsersIndexRoute = AuthSettingsUsersIndexRouteImport.update({
  id: '/settings/users/',
  path: '/settings/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFleetTrucksIndexRoute = AuthFleetTrucksIndexRouteImport.update({
  id: '/fleet/trucks/',
  path: '/fleet/trucks/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFleetTrailersIndexRoute = AuthFleetTrailersIndexRouteImport.update({
  id: '/fleet/trailers/',
  path: '/fleet/trailers/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTripsTripIdEditRoute = AuthTripsTripIdEditRouteImport.update({
  id: '/trips/$tripId/edit',
  path: '/trips/$tripId/edit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsUsersNewRoute = AuthSettingsUsersNewRouteImport.update({
  id: '/settings/users/new',
  path: '/settings/users/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMaintenanceWorkOrdersNewRoute =
  AuthMaintenanceWorkOrdersNewRouteImport.update({
    id: '/maintenance/work-orders/new',
    path: '/maintenance/work-orders/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthMaintenanceSchedulesNewRoute =
  AuthMaintenanceSchedulesNewRouteImport.update({
    id: '/maintenance/schedules/new',
    path: '/maintenance/schedules/new',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthFuelLogsNewRoute = AuthFuelLogsNewRouteImport.update({
  id: '/fuel/logs/new',
  path: '/fuel/logs/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFuelExpensesNewRoute = AuthFuelExpensesNewRouteImport.update({
  id: '/fuel/expenses/new',
  path: '/fuel/expenses/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFleetTrucksNewRoute = AuthFleetTrucksNewRouteImport.update({
  id: '/fleet/trucks/new',
  path: '/fleet/trucks/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFleetTrucksTruckIdRoute = AuthFleetTrucksTruckIdRouteImport.update({
  id: '/fleet/trucks/$truckId',
  path: '/fleet/trucks/$truckId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFleetTrailersNewRoute = AuthFleetTrailersNewRouteImport.update({
  id: '/fleet/trailers/new',
  path: '/fleet/trailers/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFleetTrailersTrailerIdRoute =
  AuthFleetTrailersTrailerIdRouteImport.update({
    id: '/fleet/trailers/$trailerId',
    path: '/fleet/trailers/$trailerId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDriversDriverIdEditRoute = AuthDriversDriverIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthDriversDriverIdRoute,
} as any)
const AuthMaintenanceWorkOrdersWorkOrderIdIndexRoute =
  AuthMaintenanceWorkOrdersWorkOrderIdIndexRouteImport.update({
    id: '/maintenance/work-orders/$workOrderId/',
    path: '/maintenance/work-orders/$workOrderId/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthFuelLogsLogIdIndexRoute = AuthFuelLogsLogIdIndexRouteImport.update({
  id: '/fuel/logs/$logId/',
  path: '/fuel/logs/$logId/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFuelExpensesExpenseIdIndexRoute =
  AuthFuelExpensesExpenseIdIndexRouteImport.update({
    id: '/fuel/expenses/$expenseId/',
    path: '/fuel/expenses/$expenseId/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSettingsUsersUserIdEditRoute =
  AuthSettingsUsersUserIdEditRouteImport.update({
    id: '/settings/users/$userId/edit',
    path: '/settings/users/$userId/edit',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthMaintenanceWorkOrdersWorkOrderIdEditRoute =
  AuthMaintenanceWorkOrdersWorkOrderIdEditRouteImport.update({
    id: '/maintenance/work-orders/$workOrderId/edit',
    path: '/maintenance/work-orders/$workOrderId/edit',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthMaintenanceSchedulesScheduleIdEditRoute =
  AuthMaintenanceSchedulesScheduleIdEditRouteImport.update({
    id: '/maintenance/schedules/$scheduleId/edit',
    path: '/maintenance/schedules/$scheduleId/edit',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthFleetTrucksTruckIdEditRoute =
  AuthFleetTrucksTruckIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthFleetTrucksTruckIdRoute,
  } as any)
const AuthFleetTrailersTrailerIdEditRoute =
  AuthFleetTrailersTrailerIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthFleetTrailersTrailerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/drivers/$driverId': typeof AuthDriversDriverIdRouteWithChildren
  '/drivers/new': typeof AuthDriversNewRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/system': typeof AuthSettingsSystemRoute
  '/trips/new': typeof AuthTripsNewRoute
  '/drivers/': typeof AuthDriversIndexRoute
  '/fuel/': typeof AuthFuelIndexRoute
  '/maintenance/': typeof AuthMaintenanceIndexRoute
  '/notifications/': typeof AuthNotificationsIndexRoute
  '/trips/': typeof AuthTripsIndexRoute
  '/drivers/$driverId/edit': typeof AuthDriversDriverIdEditRoute
  '/fleet/trailers/$trailerId': typeof AuthFleetTrailersTrailerIdRouteWithChildren
  '/fleet/trailers/new': typeof AuthFleetTrailersNewRoute
  '/fleet/trucks/$truckId': typeof AuthFleetTrucksTruckIdRouteWithChildren
  '/fleet/trucks/new': typeof AuthFleetTrucksNewRoute
  '/fuel/expenses/new': typeof AuthFuelExpensesNewRoute
  '/fuel/logs/new': typeof AuthFuelLogsNewRoute
  '/maintenance/schedules/new': typeof AuthMaintenanceSchedulesNewRoute
  '/maintenance/work-orders/new': typeof AuthMaintenanceWorkOrdersNewRoute
  '/settings/users/new': typeof AuthSettingsUsersNewRoute
  '/trips/$tripId/edit': typeof AuthTripsTripIdEditRoute
  '/fleet/trailers/': typeof AuthFleetTrailersIndexRoute
  '/fleet/trucks/': typeof AuthFleetTrucksIndexRoute
  '/settings/users/': typeof AuthSettingsUsersIndexRoute
  '/trips/$tripId/': typeof AuthTripsTripIdIndexRoute
  '/fleet/trailers/$trailerId/edit': typeof AuthFleetTrailersTrailerIdEditRoute
  '/fleet/trucks/$truckId/edit': typeof AuthFleetTrucksTruckIdEditRoute
  '/maintenance/schedules/$scheduleId/edit': typeof AuthMaintenanceSchedulesScheduleIdEditRoute
  '/maintenance/work-orders/$workOrderId/edit': typeof AuthMaintenanceWorkOrdersWorkOrderIdEditRoute
  '/settings/users/$userId/edit': typeof AuthSettingsUsersUserIdEditRoute
  '/fuel/expenses/$expenseId/': typeof AuthFuelExpensesExpenseIdIndexRoute
  '/fuel/logs/$logId/': typeof AuthFuelLogsLogIdIndexRoute
  '/maintenance/work-orders/$workOrderId/': typeof AuthMaintenanceWorkOrdersWorkOrderIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/drivers/$driverId': typeof AuthDriversDriverIdRouteWithChildren
  '/drivers/new': typeof AuthDriversNewRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/system': typeof AuthSettingsSystemRoute
  '/trips/new': typeof AuthTripsNewRoute
  '/drivers': typeof AuthDriversIndexRoute
  '/fuel': typeof AuthFuelIndexRoute
  '/maintenance': typeof AuthMaintenanceIndexRoute
  '/notifications': typeof AuthNotificationsIndexRoute
  '/trips': typeof AuthTripsIndexRoute
  '/drivers/$driverId/edit': typeof AuthDriversDriverIdEditRoute
  '/fleet/trailers/$trailerId': typeof AuthFleetTrailersTrailerIdRouteWithChildren
  '/fleet/trailers/new': typeof AuthFleetTrailersNewRoute
  '/fleet/trucks/$truckId': typeof AuthFleetTrucksTruckIdRouteWithChildren
  '/fleet/trucks/new': typeof AuthFleetTrucksNewRoute
  '/fuel/expenses/new': typeof AuthFuelExpensesNewRoute
  '/fuel/logs/new': typeof AuthFuelLogsNewRoute
  '/maintenance/schedules/new': typeof AuthMaintenanceSchedulesNewRoute
  '/maintenance/work-orders/new': typeof AuthMaintenanceWorkOrdersNewRoute
  '/settings/users/new': typeof AuthSettingsUsersNewRoute
  '/trips/$tripId/edit': typeof AuthTripsTripIdEditRoute
  '/fleet/trailers': typeof AuthFleetTrailersIndexRoute
  '/fleet/trucks': typeof AuthFleetTrucksIndexRoute
  '/settings/users': typeof AuthSettingsUsersIndexRoute
  '/trips/$tripId': typeof AuthTripsTripIdIndexRoute
  '/fleet/trailers/$trailerId/edit': typeof AuthFleetTrailersTrailerIdEditRoute
  '/fleet/trucks/$truckId/edit': typeof AuthFleetTrucksTruckIdEditRoute
  '/maintenance/schedules/$scheduleId/edit': typeof AuthMaintenanceSchedulesScheduleIdEditRoute
  '/maintenance/work-orders/$workOrderId/edit': typeof AuthMaintenanceWorkOrdersWorkOrderIdEditRoute
  '/settings/users/$userId/edit': typeof AuthSettingsUsersUserIdEditRoute
  '/fuel/expenses/$expenseId': typeof AuthFuelExpensesExpenseIdIndexRoute
  '/fuel/logs/$logId': typeof AuthFuelLogsLogIdIndexRoute
  '/maintenance/work-orders/$workOrderId': typeof AuthMaintenanceWorkOrdersWorkOrderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/drivers/$driverId': typeof AuthDriversDriverIdRouteWithChildren
  '/_auth/drivers/new': typeof AuthDriversNewRoute
  '/_auth/settings/profile': typeof AuthSettingsProfileRoute
  '/_auth/settings/system': typeof AuthSettingsSystemRoute
  '/_auth/trips/new': typeof AuthTripsNewRoute
  '/_auth/drivers/': typeof AuthDriversIndexRoute
  '/_auth/fuel/': typeof AuthFuelIndexRoute
  '/_auth/maintenance/': typeof AuthMaintenanceIndexRoute
  '/_auth/notifications/': typeof AuthNotificationsIndexRoute
  '/_auth/trips/': typeof AuthTripsIndexRoute
  '/_auth/drivers/$driverId/edit': typeof AuthDriversDriverIdEditRoute
  '/_auth/fleet/trailers/$trailerId': typeof AuthFleetTrailersTrailerIdRouteWithChildren
  '/_auth/fleet/trailers/new': typeof AuthFleetTrailersNewRoute
  '/_auth/fleet/trucks/$truckId': typeof AuthFleetTrucksTruckIdRouteWithChildren
  '/_auth/fleet/trucks/new': typeof AuthFleetTrucksNewRoute
  '/_auth/fuel/expenses/new': typeof AuthFuelExpensesNewRoute
  '/_auth/fuel/logs/new': typeof AuthFuelLogsNewRoute
  '/_auth/maintenance/schedules/new': typeof AuthMaintenanceSchedulesNewRoute
  '/_auth/maintenance/work-orders/new': typeof AuthMaintenanceWorkOrdersNewRoute
  '/_auth/settings/users/new': typeof AuthSettingsUsersNewRoute
  '/_auth/trips/$tripId/edit': typeof AuthTripsTripIdEditRoute
  '/_auth/fleet/trailers/': typeof AuthFleetTrailersIndexRoute
  '/_auth/fleet/trucks/': typeof AuthFleetTrucksIndexRoute
  '/_auth/settings/users/': typeof AuthSettingsUsersIndexRoute
  '/_auth/trips/$tripId/': typeof AuthTripsTripIdIndexRoute
  '/_auth/fleet/trailers/$trailerId/edit': typeof AuthFleetTrailersTrailerIdEditRoute
  '/_auth/fleet/trucks/$truckId/edit': typeof AuthFleetTrucksTruckIdEditRoute
  '/_auth/maintenance/schedules/$scheduleId/edit': typeof AuthMaintenanceSchedulesScheduleIdEditRoute
  '/_auth/maintenance/work-orders/$workOrderId/edit': typeof AuthMaintenanceWorkOrdersWorkOrderIdEditRoute
  '/_auth/settings/users/$userId/edit': typeof AuthSettingsUsersUserIdEditRoute
  '/_auth/fuel/expenses/$expenseId/': typeof AuthFuelExpensesExpenseIdIndexRoute
  '/_auth/fuel/logs/$logId/': typeof AuthFuelLogsLogIdIndexRoute
  '/_auth/maintenance/work-orders/$workOrderId/': typeof AuthMaintenanceWorkOrdersWorkOrderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/dashboard'
    | '/drivers/$driverId'
    | '/drivers/new'
    | '/settings/profile'
    | '/settings/system'
    | '/trips/new'
    | '/drivers/'
    | '/fuel/'
    | '/maintenance/'
    | '/notifications/'
    | '/trips/'
    | '/drivers/$driverId/edit'
    | '/fleet/trailers/$trailerId'
    | '/fleet/trailers/new'
    | '/fleet/trucks/$truckId'
    | '/fleet/trucks/new'
    | '/fuel/expenses/new'
    | '/fuel/logs/new'
    | '/maintenance/schedules/new'
    | '/maintenance/work-orders/new'
    | '/settings/users/new'
    | '/trips/$tripId/edit'
    | '/fleet/trailers/'
    | '/fleet/trucks/'
    | '/settings/users/'
    | '/trips/$tripId/'
    | '/fleet/trailers/$trailerId/edit'
    | '/fleet/trucks/$truckId/edit'
    | '/maintenance/schedules/$scheduleId/edit'
    | '/maintenance/work-orders/$workOrderId/edit'
    | '/settings/users/$userId/edit'
    | '/fuel/expenses/$expenseId/'
    | '/fuel/logs/$logId/'
    | '/maintenance/work-orders/$workOrderId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/dashboard'
    | '/drivers/$driverId'
    | '/drivers/new'
    | '/settings/profile'
    | '/settings/system'
    | '/trips/new'
    | '/drivers'
    | '/fuel'
    | '/maintenance'
    | '/notifications'
    | '/trips'
    | '/drivers/$driverId/edit'
    | '/fleet/trailers/$trailerId'
    | '/fleet/trailers/new'
    | '/fleet/trucks/$truckId'
    | '/fleet/trucks/new'
    | '/fuel/expenses/new'
    | '/fuel/logs/new'
    | '/maintenance/schedules/new'
    | '/maintenance/work-orders/new'
    | '/settings/users/new'
    | '/trips/$tripId/edit'
    | '/fleet/trailers'
    | '/fleet/trucks'
    | '/settings/users'
    | '/trips/$tripId'
    | '/fleet/trailers/$trailerId/edit'
    | '/fleet/trucks/$truckId/edit'
    | '/maintenance/schedules/$scheduleId/edit'
    | '/maintenance/work-orders/$workOrderId/edit'
    | '/settings/users/$userId/edit'
    | '/fuel/expenses/$expenseId'
    | '/fuel/logs/$logId'
    | '/maintenance/work-orders/$workOrderId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/login'
    | '/_auth/dashboard'
    | '/_auth/drivers/$driverId'
    | '/_auth/drivers/new'
    | '/_auth/settings/profile'
    | '/_auth/settings/system'
    | '/_auth/trips/new'
    | '/_auth/drivers/'
    | '/_auth/fuel/'
    | '/_auth/maintenance/'
    | '/_auth/notifications/'
    | '/_auth/trips/'
    | '/_auth/drivers/$driverId/edit'
    | '/_auth/fleet/trailers/$trailerId'
    | '/_auth/fleet/trailers/new'
    | '/_auth/fleet/trucks/$truckId'
    | '/_auth/fleet/trucks/new'
    | '/_auth/fuel/expenses/new'
    | '/_auth/fuel/logs/new'
    | '/_auth/maintenance/schedules/new'
    | '/_auth/maintenance/work-orders/new'
    | '/_auth/settings/users/new'
    | '/_auth/trips/$tripId/edit'
    | '/_auth/fleet/trailers/'
    | '/_auth/fleet/trucks/'
    | '/_auth/settings/users/'
    | '/_auth/trips/$tripId/'
    | '/_auth/fleet/trailers/$trailerId/edit'
    | '/_auth/fleet/trucks/$truckId/edit'
    | '/_auth/maintenance/schedules/$scheduleId/edit'
    | '/_auth/maintenance/work-orders/$workOrderId/edit'
    | '/_auth/settings/users/$userId/edit'
    | '/_auth/fuel/expenses/$expenseId/'
    | '/_auth/fuel/logs/$logId/'
    | '/_auth/maintenance/work-orders/$workOrderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/trips/': {
      id: '/_auth/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof AuthTripsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notifications/': {
      id: '/_auth/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthNotificationsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/maintenance/': {
      id: '/_auth/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof AuthMaintenanceIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fuel/': {
      id: '/_auth/fuel/'
      path: '/fuel'
      fullPath: '/fuel/'
      preLoaderRoute: typeof AuthFuelIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/drivers/': {
      id: '/_auth/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof AuthDriversIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/trips/new': {
      id: '/_auth/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof AuthTripsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/system': {
      id: '/_auth/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof AuthSettingsSystemRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/profile': {
      id: '/_auth/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/drivers/new': {
      id: '/_auth/drivers/new'
      path: '/drivers/new'
      fullPath: '/drivers/new'
      preLoaderRoute: typeof AuthDriversNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/drivers/$driverId': {
      id: '/_auth/drivers/$driverId'
      path: '/drivers/$driverId'
      fullPath: '/drivers/$driverId'
      preLoaderRoute: typeof AuthDriversDriverIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/trips/$tripId/': {
      id: '/_auth/trips/$tripId/'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId/'
      preLoaderRoute: typeof AuthTripsTripIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/users/': {
      id: '/_auth/settings/users/'
      path: '/settings/users'
      fullPath: '/settings/users/'
      preLoaderRoute: typeof AuthSettingsUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fleet/trucks/': {
      id: '/_auth/fleet/trucks/'
      path: '/fleet/trucks'
      fullPath: '/fleet/trucks/'
      preLoaderRoute: typeof AuthFleetTrucksIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fleet/trailers/': {
      id: '/_auth/fleet/trailers/'
      path: '/fleet/trailers'
      fullPath: '/fleet/trailers/'
      preLoaderRoute: typeof AuthFleetTrailersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/trips/$tripId/edit': {
      id: '/_auth/trips/$tripId/edit'
      path: '/trips/$tripId/edit'
      fullPath: '/trips/$tripId/edit'
      preLoaderRoute: typeof AuthTripsTripIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/users/new': {
      id: '/_auth/settings/users/new'
      path: '/settings/users/new'
      fullPath: '/settings/users/new'
      preLoaderRoute: typeof AuthSettingsUsersNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/maintenance/work-orders/new': {
      id: '/_auth/maintenance/work-orders/new'
      path: '/maintenance/work-orders/new'
      fullPath: '/maintenance/work-orders/new'
      preLoaderRoute: typeof AuthMaintenanceWorkOrdersNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/maintenance/schedules/new': {
      id: '/_auth/maintenance/schedules/new'
      path: '/maintenance/schedules/new'
      fullPath: '/maintenance/schedules/new'
      preLoaderRoute: typeof AuthMaintenanceSchedulesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fuel/logs/new': {
      id: '/_auth/fuel/logs/new'
      path: '/fuel/logs/new'
      fullPath: '/fuel/logs/new'
      preLoaderRoute: typeof AuthFuelLogsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fuel/expenses/new': {
      id: '/_auth/fuel/expenses/new'
      path: '/fuel/expenses/new'
      fullPath: '/fuel/expenses/new'
      preLoaderRoute: typeof AuthFuelExpensesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fleet/trucks/new': {
      id: '/_auth/fleet/trucks/new'
      path: '/fleet/trucks/new'
      fullPath: '/fleet/trucks/new'
      preLoaderRoute: typeof AuthFleetTrucksNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fleet/trucks/$truckId': {
      id: '/_auth/fleet/trucks/$truckId'
      path: '/fleet/trucks/$truckId'
      fullPath: '/fleet/trucks/$truckId'
      preLoaderRoute: typeof AuthFleetTrucksTruckIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fleet/trailers/new': {
      id: '/_auth/fleet/trailers/new'
      path: '/fleet/trailers/new'
      fullPath: '/fleet/trailers/new'
      preLoaderRoute: typeof AuthFleetTrailersNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fleet/trailers/$trailerId': {
      id: '/_auth/fleet/trailers/$trailerId'
      path: '/fleet/trailers/$trailerId'
      fullPath: '/fleet/trailers/$trailerId'
      preLoaderRoute: typeof AuthFleetTrailersTrailerIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/drivers/$driverId/edit': {
      id: '/_auth/drivers/$driverId/edit'
      path: '/edit'
      fullPath: '/drivers/$driverId/edit'
      preLoaderRoute: typeof AuthDriversDriverIdEditRouteImport
      parentRoute: typeof AuthDriversDriverIdRoute
    }
    '/_auth/maintenance/work-orders/$workOrderId/': {
      id: '/_auth/maintenance/work-orders/$workOrderId/'
      path: '/maintenance/work-orders/$workOrderId'
      fullPath: '/maintenance/work-orders/$workOrderId/'
      preLoaderRoute: typeof AuthMaintenanceWorkOrdersWorkOrderIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fuel/logs/$logId/': {
      id: '/_auth/fuel/logs/$logId/'
      path: '/fuel/logs/$logId'
      fullPath: '/fuel/logs/$logId/'
      preLoaderRoute: typeof AuthFuelLogsLogIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fuel/expenses/$expenseId/': {
      id: '/_auth/fuel/expenses/$expenseId/'
      path: '/fuel/expenses/$expenseId'
      fullPath: '/fuel/expenses/$expenseId/'
      preLoaderRoute: typeof AuthFuelExpensesExpenseIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/users/$userId/edit': {
      id: '/_auth/settings/users/$userId/edit'
      path: '/settings/users/$userId/edit'
      fullPath: '/settings/users/$userId/edit'
      preLoaderRoute: typeof AuthSettingsUsersUserIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/maintenance/work-orders/$workOrderId/edit': {
      id: '/_auth/maintenance/work-orders/$workOrderId/edit'
      path: '/maintenance/work-orders/$workOrderId/edit'
      fullPath: '/maintenance/work-orders/$workOrderId/edit'
      preLoaderRoute: typeof AuthMaintenanceWorkOrdersWorkOrderIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/maintenance/schedules/$scheduleId/edit': {
      id: '/_auth/maintenance/schedules/$scheduleId/edit'
      path: '/maintenance/schedules/$scheduleId/edit'
      fullPath: '/maintenance/schedules/$scheduleId/edit'
      preLoaderRoute: typeof AuthMaintenanceSchedulesScheduleIdEditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fleet/trucks/$truckId/edit': {
      id: '/_auth/fleet/trucks/$truckId/edit'
      path: '/edit'
      fullPath: '/fleet/trucks/$truckId/edit'
      preLoaderRoute: typeof AuthFleetTrucksTruckIdEditRouteImport
      parentRoute: typeof AuthFleetTrucksTruckIdRoute
    }
    '/_auth/fleet/trailers/$trailerId/edit': {
      id: '/_auth/fleet/trailers/$trailerId/edit'
      path: '/edit'
      fullPath: '/fleet/trailers/$trailerId/edit'
      preLoaderRoute: typeof AuthFleetTrailersTrailerIdEditRouteImport
      parentRoute: typeof AuthFleetTrailersTrailerIdRoute
    }
  }
}

interface AuthDriversDriverIdRouteChildren {
  AuthDriversDriverIdEditRoute: typeof AuthDriversDriverIdEditRoute
}

const AuthDriversDriverIdRouteChildren: AuthDriversDriverIdRouteChildren = {
  AuthDriversDriverIdEditRoute: AuthDriversDriverIdEditRoute,
}

const AuthDriversDriverIdRouteWithChildren =
  AuthDriversDriverIdRoute._addFileChildren(AuthDriversDriverIdRouteChildren)

interface AuthFleetTrailersTrailerIdRouteChildren {
  AuthFleetTrailersTrailerIdEditRoute: typeof AuthFleetTrailersTrailerIdEditRoute
}

const AuthFleetTrailersTrailerIdRouteChildren: AuthFleetTrailersTrailerIdRouteChildren =
  {
    AuthFleetTrailersTrailerIdEditRoute: AuthFleetTrailersTrailerIdEditRoute,
  }

const AuthFleetTrailersTrailerIdRouteWithChildren =
  AuthFleetTrailersTrailerIdRoute._addFileChildren(
    AuthFleetTrailersTrailerIdRouteChildren,
  )

interface AuthFleetTrucksTruckIdRouteChildren {
  AuthFleetTrucksTruckIdEditRoute: typeof AuthFleetTrucksTruckIdEditRoute
}

const AuthFleetTrucksTruckIdRouteChildren: AuthFleetTrucksTruckIdRouteChildren =
  {
    AuthFleetTrucksTruckIdEditRoute: AuthFleetTrucksTruckIdEditRoute,
  }

const AuthFleetTrucksTruckIdRouteWithChildren =
  AuthFleetTrucksTruckIdRoute._addFileChildren(
    AuthFleetTrucksTruckIdRouteChildren,
  )

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDriversDriverIdRoute: typeof AuthDriversDriverIdRouteWithChildren
  AuthDriversNewRoute: typeof AuthDriversNewRoute
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
  AuthSettingsSystemRoute: typeof AuthSettingsSystemRoute
  AuthTripsNewRoute: typeof AuthTripsNewRoute
  AuthDriversIndexRoute: typeof AuthDriversIndexRoute
  AuthFuelIndexRoute: typeof AuthFuelIndexRoute
  AuthMaintenanceIndexRoute: typeof AuthMaintenanceIndexRoute
  AuthNotificationsIndexRoute: typeof AuthNotificationsIndexRoute
  AuthTripsIndexRoute: typeof AuthTripsIndexRoute
  AuthFleetTrailersTrailerIdRoute: typeof AuthFleetTrailersTrailerIdRouteWithChildren
  AuthFleetTrailersNewRoute: typeof AuthFleetTrailersNewRoute
  AuthFleetTrucksTruckIdRoute: typeof AuthFleetTrucksTruckIdRouteWithChildren
  AuthFleetTrucksNewRoute: typeof AuthFleetTrucksNewRoute
  AuthFuelExpensesNewRoute: typeof AuthFuelExpensesNewRoute
  AuthFuelLogsNewRoute: typeof AuthFuelLogsNewRoute
  AuthMaintenanceSchedulesNewRoute: typeof AuthMaintenanceSchedulesNewRoute
  AuthMaintenanceWorkOrdersNewRoute: typeof AuthMaintenanceWorkOrdersNewRoute
  AuthSettingsUsersNewRoute: typeof AuthSettingsUsersNewRoute
  AuthTripsTripIdEditRoute: typeof AuthTripsTripIdEditRoute
  AuthFleetTrailersIndexRoute: typeof AuthFleetTrailersIndexRoute
  AuthFleetTrucksIndexRoute: typeof AuthFleetTrucksIndexRoute
  AuthSettingsUsersIndexRoute: typeof AuthSettingsUsersIndexRoute
  AuthTripsTripIdIndexRoute: typeof AuthTripsTripIdIndexRoute
  AuthMaintenanceSchedulesScheduleIdEditRoute: typeof AuthMaintenanceSchedulesScheduleIdEditRoute
  AuthMaintenanceWorkOrdersWorkOrderIdEditRoute: typeof AuthMaintenanceWorkOrdersWorkOrderIdEditRoute
  AuthSettingsUsersUserIdEditRoute: typeof AuthSettingsUsersUserIdEditRoute
  AuthFuelExpensesExpenseIdIndexRoute: typeof AuthFuelExpensesExpenseIdIndexRoute
  AuthFuelLogsLogIdIndexRoute: typeof AuthFuelLogsLogIdIndexRoute
  AuthMaintenanceWorkOrdersWorkOrderIdIndexRoute: typeof AuthMaintenanceWorkOrdersWorkOrderIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDriversDriverIdRoute: AuthDriversDriverIdRouteWithChildren,
  AuthDriversNewRoute: AuthDriversNewRoute,
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
  AuthSettingsSystemRoute: AuthSettingsSystemRoute,
  AuthTripsNewRoute: AuthTripsNewRoute,
  AuthDriversIndexRoute: AuthDriversIndexRoute,
  AuthFuelIndexRoute: AuthFuelIndexRoute,
  AuthMaintenanceIndexRoute: AuthMaintenanceIndexRoute,
  AuthNotificationsIndexRoute: AuthNotificationsIndexRoute,
  AuthTripsIndexRoute: AuthTripsIndexRoute,
  AuthFleetTrailersTrailerIdRoute: AuthFleetTrailersTrailerIdRouteWithChildren,
  AuthFleetTrailersNewRoute: AuthFleetTrailersNewRoute,
  AuthFleetTrucksTruckIdRoute: AuthFleetTrucksTruckIdRouteWithChildren,
  AuthFleetTrucksNewRoute: AuthFleetTrucksNewRoute,
  AuthFuelExpensesNewRoute: AuthFuelExpensesNewRoute,
  AuthFuelLogsNewRoute: AuthFuelLogsNewRoute,
  AuthMaintenanceSchedulesNewRoute: AuthMaintenanceSchedulesNewRoute,
  AuthMaintenanceWorkOrdersNewRoute: AuthMaintenanceWorkOrdersNewRoute,
  AuthSettingsUsersNewRoute: AuthSettingsUsersNewRoute,
  AuthTripsTripIdEditRoute: AuthTripsTripIdEditRoute,
  AuthFleetTrailersIndexRoute: AuthFleetTrailersIndexRoute,
  AuthFleetTrucksIndexRoute: AuthFleetTrucksIndexRoute,
  AuthSettingsUsersIndexRoute: AuthSettingsUsersIndexRoute,
  AuthTripsTripIdIndexRoute: AuthTripsTripIdIndexRoute,
  AuthMaintenanceSchedulesScheduleIdEditRoute:
    AuthMaintenanceSchedulesScheduleIdEditRoute,
  AuthMaintenanceWorkOrdersWorkOrderIdEditRoute:
    AuthMaintenanceWorkOrdersWorkOrderIdEditRoute,
  AuthSettingsUsersUserIdEditRoute: AuthSettingsUsersUserIdEditRoute,
  AuthFuelExpensesExpenseIdIndexRoute: AuthFuelExpensesExpenseIdIndexRoute,
  AuthFuelLogsLogIdIndexRoute: AuthFuelLogsLogIdIndexRoute,
  AuthMaintenanceWorkOrdersWorkOrderIdIndexRoute:
    AuthMaintenanceWorkOrdersWorkOrderIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
