"""update models enum status and vehicle_iamge

Revision ID: 3bc2a59680c9
Revises: c3b4cb3a1df7
Create Date: 2026-03-15 10:53:47.424468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc2a59680c9'
down_revision: Union[str, Sequence[str], None] = 'c3b4cb3a1df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trailers', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('trucks', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trucks', 'image_url')
    op.drop_column('trailers', 'image_url')
    # ### end Alembic commands ###
