"""initial_schema

Revision ID: 8972ed85b94d
Revises: 
Create Date: 2026-03-07 15:52:03.041697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8972ed85b94d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trailers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('make', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='trailerstatus'), nullable=False),
    sa.Column('type', sa.Enum('flatbed', 'refrigerated', 'tanker', 'box', 'other', name='trailertype'), nullable=False),
    sa.Column('capacity_tons', sa.Float(), nullable=True),
    sa.Column('assigned_trip_id', sa.String(length=36), nullable=True),
    sa.Column('insurance_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspection_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trailers_id'), 'trailers', ['id'], unique=False)
    op.create_index(op.f('ix_trailers_plate_number'), 'trailers', ['plate_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'DISPATCHER', 'DRIVER', 'MECHANIC', 'FINANCE', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.Column('reset_password_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='driverstatus'), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('license_class', sa.String(length=20), nullable=False),
    sa.Column('license_expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('hire_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('trip_assigned', 'trip_status_changed', 'work_order_assigned', 'maintenance_due', 'document_expiring', 'fuel_logged', 'expense_submitted', 'system', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('action_url', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_name', sa.String(length=200), nullable=True),
    sa.Column('org_timezone', sa.String(length=50), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fuel_unit', sa.String(length=20), nullable=False),
    sa.Column('distance_unit', sa.String(length=20), nullable=False),
    sa.Column('maintenance_warning_days', sa.Integer(), nullable=False),
    sa.Column('license_expiry_warning_days', sa.Integer(), nullable=False),
    sa.Column('document_expiry_warning_days', sa.Integer(), nullable=False),
    sa.Column('email_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('maintenance_alerts', sa.Boolean(), nullable=False),
    sa.Column('trip_status_alerts', sa.Boolean(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('default_language', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trailer_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trailer_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('insurance', 'registration', 'inspection', 'other', name='vehicledoctype'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['trailer_id'], ['trailers.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trucks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('make', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'in-progress', name='truckstatus'), nullable=False),
    sa.Column('odometer_km', sa.Float(), nullable=False),
    sa.Column('fuel_type', sa.Enum('diesel', 'petrol', 'electric', 'hybrid', name='fueltype'), nullable=False),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('assigned_driver_id', sa.String(length=36), nullable=True),
    sa.Column('current_trip_id', sa.String(length=36), nullable=True),
    sa.Column('insurance_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspection_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trucks_id'), 'trucks', ['id'], unique=False)
    op.create_index(op.f('ix_trucks_plate_number'), 'trucks', ['plate_number'], unique=True)
    op.create_table('user_oauth',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=False),
    sa.Column('provider_email', sa.String(length=120), nullable=False),
    sa.Column('access_token', sa.String(length=500), nullable=True),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user')
    )
    op.create_index(op.f('ix_user_oauth_provider_user_id'), 'user_oauth', ['provider_user_id'], unique=False)
    op.create_table('driver_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('license', 'medical', 'contract', 'certificate', 'other', name='driverdoctype'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('truck_id', sa.String(length=36), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('interval_type', sa.Enum('km', 'days', 'months', name='serviceintervaltype'), nullable=False),
    sa.Column('interval_value', sa.Integer(), nullable=False),
    sa.Column('last_service_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_service_odometer', sa.Float(), nullable=True),
    sa.Column('next_service_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_service_odometer', sa.Float(), nullable=True),
    sa.Column('reminder_days_before', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trip_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'en-route', 'completed', 'cancelled', name='tripstatus'), nullable=False),
    sa.Column('origin', sa.String(length=200), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('cargo_description', sa.Text(), nullable=True),
    sa.Column('cargo_weight_tons', sa.Float(), nullable=True),
    sa.Column('assigned_truck_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_trailer_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_driver_id', sa.String(length=36), nullable=True),
    sa.Column('dispatched_by', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('origin_lat', sa.Float(), nullable=True),
    sa.Column('origin_lng', sa.Float(), nullable=True),
    sa.Column('destination_lat', sa.Float(), nullable=True),
    sa.Column('destination_lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['assigned_trailer_id'], ['trailers.id'], ),
    sa.ForeignKeyConstraint(['assigned_truck_id'], ['trucks.id'], ),
    sa.ForeignKeyConstraint(['dispatched_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_index(op.f('ix_trips_trip_number'), 'trips', ['trip_number'], unique=True)
    op.create_table('truck_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('truck_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('insurance', 'registration', 'inspection', 'other', name='vehicledoctype'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_order_number', sa.String(length=20), nullable=False),
    sa.Column('truck_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_mechanic_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in-progress', 'completed', 'overdue', name='workorderstatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='workorderpriority'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('odometer_at_service', sa.Float(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_mechanic_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_id'), 'work_orders', ['id'], unique=False)
    op.create_index(op.f('ix_work_orders_work_order_number'), 'work_orders', ['work_order_number'], unique=True)
    op.create_table('expenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('fuel', 'maintenance', 'tolls', 'tyres', 'insurance', 'licensing', 'salary', 'other', name='expensecategory'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('truck_id', sa.String(length=36), nullable=True),
    sa.Column('driver_id', sa.String(length=36), nullable=True),
    sa.Column('trip_id', sa.String(length=36), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('expense_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('truck_id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=True),
    sa.Column('litres', sa.Float(), nullable=False),
    sa.Column('price_per_litre', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('odometer_at_fuel', sa.Float(), nullable=False),
    sa.Column('station_name', sa.String(length=120), nullable=True),
    sa.Column('station_location', sa.String(length=200), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('truck_id', sa.String(length=36), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('odometer_at_service', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('performed_by', sa.String(length=36), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=True),
    sa.Column('service_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_location_pings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recorded_by', sa.String(length=36), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_location_pings_trip_id'), 'trip_location_pings', ['trip_id'], unique=False)
    op.create_table('work_order_parts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=False),
    sa.Column('part_name', sa.String(length=120), nullable=False),
    sa.Column('part_number', sa.String(length=60), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_order_parts')
    op.drop_index(op.f('ix_trip_location_pings_trip_id'), table_name='trip_location_pings')
    op.drop_table('trip_location_pings')
    op.drop_table('service_records')
    op.drop_table('fuel_logs')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_work_orders_work_order_number'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_table('truck_documents')
    op.drop_index(op.f('ix_trips_trip_number'), table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_table('service_schedules')
    op.drop_table('driver_documents')
    op.drop_index(op.f('ix_user_oauth_provider_user_id'), table_name='user_oauth')
    op.drop_table('user_oauth')
    op.drop_index(op.f('ix_trucks_plate_number'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_id'), table_name='trucks')
    op.drop_table('trucks')
    op.drop_table('trailer_documents')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trailers_plate_number'), table_name='trailers')
    op.drop_index(op.f('ix_trailers_id'), table_name='trailers')
    op.drop_table('trailers')
    # ### end Alembic commands ###
