"""add vehicle spec columns

Revision ID: c3b4cb3a1df7
Revises: 8972ed85b94d
Create Date: 2026-03-14 18:28:11.343996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b4cb3a1df7'
down_revision: Union[str, Sequence[str], None] = '8972ed85b94d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trailers', sa.Column('axles', sa.Integer(), nullable=True))
    op.add_column('trucks', sa.Column('wheel_config', sa.String(length=20), nullable=True))
    op.add_column('trucks', sa.Column('gross_weight_tons', sa.Float(), nullable=True))
    op.add_column('trucks', sa.Column('axle_load_tons', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trucks', 'axle_load_tons')
    op.drop_column('trucks', 'gross_weight_tons')
    op.drop_column('trucks', 'wheel_config')
    op.drop_column('trailers', 'axles')
    # ### end Alembic commands ###
